# Generated by Django 4.2.4 on 2023-10-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_group_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
