# Generated by Django 4.2.4 on 2023-10-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_group_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='default_group_id',
        ),
    ]
