# Generated by Django 4.2.4 on 2023-10-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_group_default_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='age',
        ),
        migrations.RemoveField(
            model_name='training',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='training',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='training',
            name='members',
        ),
        migrations.RemoveField(
            model_name='training',
            name='name',
        ),
        migrations.RemoveField(
            model_name='training',
            name='training_date',
        ),
        migrations.RemoveField(
            model_name='training',
            name='training_photos',
        ),
        migrations.AddField(
            model_name='training',
            name='completion_training_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.member'),
        ),
        migrations.AddField(
            model_name='training',
            name='start_training_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='training_photo',
            field=models.ImageField(blank=True, null=True, upload_to='training_photos/'),
        ),
        migrations.AlterField(
            model_name='training',
            name='topic_trained',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
